# Generated by Django 4.0.3 on 2022-04-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='price',
        ),
    ]
