# Generated by Django 4.0.3 on 2022-04-21 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_bid_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['listing', '-bid']},
        ),
        migrations.AlterModelOptions(
            name='commend',
            options={'ordering': ['listing', '-createTime']},
        ),
        migrations.RenameField(
            model_name='commend',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='commend',
            name='id',
        ),
        migrations.AddField(
            model_name='commend',
            name='ID',
            field=models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commend',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created time'),
            preserve_default=False,
        ),
    ]
